version: "2.0"

services:
#  fluentd:
#    build:
#      context: .
#      dockerfile: Dockerfile-fluentd
#    volumes:
#    - ./_fluentd/etc:/fluentd/etc
#    - nginxlog:/var/log/nginx:ro
#    environment:
#    - FLUENTD_CONF=fluent.conf
#    ports:
#    - 24224:24224
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80
  django:
    image: django
    ports:
    - 8000:8000